### ISSUE TITLE
Hacktoberfest 2022 - Start here!

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hyde#211]
## Welcome to Hacktoberfest 2022!

This post serves as a living document for the HydePHP organization.

### Open Hacktoberfest Issues

- [ ] https://github.com/hydephp/hyde/issues/212

### Quick Links

Here are some links to resources to get you started.
- [The Hyde Project (HydePHP/Hyde)](https://github.com/hydephp/hyde)
- [The Core Framework (HydePHP/Framework)](https://github.com/hydephp/framework)
- [The Development Monorepo (HydePHP/Develop)](https://github.com/hydephp/develop)
- [Developer/Community Resources](https://hydephp.com/community)
- [Official Documentation](https://hydephp.com/docs/master/)
- [Contribution Guide](https://hydephp.com/contributing)

## Developer Resources (excerpt)

> This is an excerpt from the developer resources page, which I highly recommend you read! You'll find it here: https://hydephp.com/community.

### How HydePHP is Structured

**HydePHP consists of a few core components, and development is done in a monorepo.**

This means that when contributing to the code, we submit the code to a single "mono" repository where the code is automatically split into separate read-only repositories for each component.

The two most important components are **Hyde** and **Framework**. We also use **HydeFront** for frontend assets.

#### Hyde/Hyde - The HydePHP Project

**The Hyde package is what the end-user sees and interacts with.** When creating a new HydePHP site, this is done using the Hyde project. The package contains all the necessary files to run a HydePHP site and bootstraps the entire system. _Equivalent to Laravel/Laravel_

#### Hyde/Framework - The Core Framework

**The Framework package holds most of the logic of the Hyde framework.** This is where all the data models, static site generators, HydeCLI commands, Blade views, and more, are stored. Having this in a package makes it much easier to version and update using Composer. _Equivalent to Laravel/Framework_

#### Hyde/HydeFront - The Frontend Assets

**The HydeFront package contains stylesheets and scripts** to help make HydePHP sites accessible and interactive. It also includes a pre-compiled TailwindCSS file containing all the styles needed for the built-in Blade templates.

**Comment by caendesilva** [comment]
Wondering what to contribute? Right now there aren't that many issues so I'm absolutely open to suggestions and initiatives!

Here are some ideas, including a bunch of **no code** ones!

- Update the documentation
- Update the website
- Create infographics (or just graphics in general)
- Create demo/instructional videos
- Guest blog posts
- Write more tests (We have PHPUnit/Pest and Dusk, but am open to adding Cypress again)
- **And the best for last:** demo sites, lots and lots of demo sites! Why not create a HydePHP site for your side business, book club, or sports team?

**Comment by minhaj-313** [comment]
Hi, I want to Start Contribution in your Project,
I want to add scrollbar CSS can you Assign me for Hacktoberfest

**Comment by caendesilva** [comment]
> Hi, I want to Start Contribution in your Project, I want to add scrollbar CSS can you Assign me for Hacktoberfest

Hey there! Welcome to HydePHP! To participate in Hacktoberfest, all you need to do is to create a pull request. If the PR qualifies for the [Hacktoberfest rules](https://hacktoberfest.com/participation/#contributors) I'll tag it with the Hacktoberfest tag.

To increase your changes of the PR being accepted, please make sure to describe what value your contribution adds to the project. In general, the default HydePHP theme is designed to be very minimal and un-opinionated.

Let me know if you have any more questions!

**Comment by minhaj-313** [comment]
> > Hi, I want to Start Contribution in your Project, I want to add scrollbar CSS can you Assign me for Hacktoberfest
> 
> Hey there! Welcome to HydePHP! To participate in Hacktoberfest, all you need to do is to create a pull request. If the PR qualifies for the [Hacktoberfest rules](https://hacktoberfest.com/participation/#contributors) I'll tag it with the Hacktoberfest tag.
> 
> To increase your changes of the PR being accepted, please make sure to describe what value your contribution adds to the project. In general, the default HydePHP theme is designed to be very minimal and un-opinionated.
> 
> Let me know if you have any more questions!

I want to work on Scroll Bar.
I am beginner in hacktoberfest but I will try my best did you assign it to me

**Comment by caendesilva** [comment]
> > > Hi, I want to Start Contribution in your Project, I want to add scrollbar CSS can you Assign me for Hacktoberfest
> > 
> > 
> > Hey there! Welcome to HydePHP! To participate in Hacktoberfest, all you need to do is to create a pull request. If the PR qualifies for the [Hacktoberfest rules](https://hacktoberfest.com/participation/#contributors) I'll tag it with the Hacktoberfest tag.
> > To increase your changes of the PR being accepted, please make sure to describe what value your contribution adds to the project. In general, the default HydePHP theme is designed to be very minimal and un-opinionated.
> > Let me know if you have any more questions!
> 
> I want to work on Scroll Bar. I am beginner in hacktoberfest but I will try my best did you assign it to me

You're free to start coding on anything you want, when you feel ready you'll need to submit a pull request. That's when I'll assign the Hacktoberfest tag for you. Here are some resources for how to create a pull request: https://hacktoberfest.com/participation/#beginner-resources

**Comment by minhaj-313** [comment]
Sir I did follow all rules and try to code but I did not understand where to add my scroll bar CSS, Actually I want to add a CSS Scroll bar it looks very attractive but I don't know where I want to add this CSS, after giving time on this project finally I find app.css file then I add my code in this file I don't know I do correct or wrong can you please see this if it is right then you can tell me it is right then I will pull my request. If you agree with my code then you will tell me.
Thank You So Much Sir.
here you can see my code : https://github.com/minhaj-313/hyde

**Comment by caendesilva** [comment]
> Sir I did follow all rules and try to code but I did not understand where to add my scroll bar CSS, Actually I want to add a CSS Scroll bar it looks very attractive but I don't know where I want to add this CSS, after giving time on this project finally I find app.css file then I add my code in this file I don't know I do correct or wrong can you please see this if it is right then you can tell me it is right then I will pull my request. If you agree with my code then you will tell me. Thank You So Much Sir. here you can see my code : https://github.com/minhaj-313/hyde

Okay I took a quick look at your contribution. The stylesheets for HydePHP are managed in a package called HydeFront, this link is where you would add custom styles for the package: https://github.com/hydephp/develop/blob/master/packages/hydefront/hyde.scss

They could also be added in this file: https://github.com/hydephp/develop/blob/master/resources/assets/app.css

**Comment by minhaj-313** [comment]
> > Sir I did follow all rules and try to code but I did not understand where to add my scroll bar CSS, Actually I want to add a CSS Scroll bar it looks very attractive but I don't know where I want to add this CSS, after giving time on this project finally I find app.css file then I add my code in this file I don't know I do correct or wrong can you please see this if it is right then you can tell me it is right then I will pull my request. If you agree with my code then you will tell me. Thank You So Much Sir. here you can see my code : https://github.com/minhaj-313/hyde
> 
> Okay I took a quick look at your contribution. The stylesheets for HydePHP are managed in a package called HydeFront, this link is where you would add custom styles for the package: https://github.com/hydephp/develop/blob/master/packages/hydefront/hyde.scss
> 
> They could also be added in this file: https://github.com/hydephp/develop/blob/master/resources/assets/app.css
> 
> So, you would make your edits in one of those files. Then create a pull request in the https://github.com/hydephp/develop repository.

I did Make PR if it right then merges it for hactoberfest if it is not right then suggest me what can I do next,
and also thank you for guiding me,

**Comment by caendesilva** [comment]
Closing as Hacktoberfest 2022 is sadly over. But contributions to HydePHP is always welcome! Thanks for this season, I'm already looking forward to the next!
