### ISSUE TITLE
Compiled images (on github pages) not working as expected

### ISSUE THREAD

**Issue by rominronin** [hydephp/hyde#239]
The image on the following page has tearing artefacts (the two lines streaking across the image):
https://rominronin.github.io/posts/2023/podcasting

The original image doesn't have these lines.

On the following page, the image is broken:
https://rominronin.github.io/posts/2023/new-website

I'm using the github actions from the blog post:
https://hydephp.com/posts/github-actions-deployment

Is this related to HydePHP or github pages? Any ideas what's causing this or how to overcome it? Thanks

**Comment by caendesilva** [comment]
> Thanks, it's better to put the issue in the right place.

No worries, GitHub makes it really easy to transfer issues!

> The issue is not _quite_ fixed yet though: this is what the newly created image looks like now:
> There were two such streaks, now it's only one. Still corrupted, as there should be none.

Is this after setting the `.gitattributes` and pushing with a new filename?

**Comment by caendesilva** [comment]
What operating system are you on? If you are on Linux/Mac, can you try running the following commands on the original image file and send me the output? 

```bash
sha256sum podcast-cover-image.jpg
file podcast-cover-image.jpg
head -c 128 podcast-cover-image.jpg  | xxd
```

```
# $ sha256sum podcast-cover-image.jpg
4b0c7fe15031d10da1c4ba5fd3fb0d724f944588d338cef995610dc1184b201c  podcast-cover-image.jpg

# $ file podcast-cover-image.jpg
podcast-cover-image.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=9, PhotometricIntepretation=RGB, orientation=upper-left, xresolution=122, yresolution=130, resolutionunit=2, software=Snapseed 2.22.412829873, datetime=2023:04:20 12:19:01], baseline, precision 8, 1280x720, components 3

# $ head -c 128 podcast-cover-image.jpg  | xxd
00000000: ffd8 ffe1 022e 4578 6966 0000 4d4d 002a  ......Exif..MM.*
00000010: 0000 0008 0009 0106 0003 0000 0001 0002  ................
00000020: 0000 0112 0003 0000 0001 0001 0000 011a  ................
00000030: 0005 0000 0001 0000 007a 011b 0005 0000  .........z......
00000040: 0001 0000 0082 0128 0003 0000 0001 0002  .......(........
00000050: 0000 0131 0002 0000 0018 0000 008a 0132  ...1...........2
00000060: 0002 0000 0014 0000 00a2 0213 0003 0000  ................
00000070: 0001 0001 0000 8769 0004 0000 0001 0000  .......i........
```

This would help me try to rule out any corruption in the file. Also,  I'm more familiar with the PNG format, do you get the same issues with PNG files?

> PNG files have a magic number - an 8-byte header - which contains two newlines, one in Dos-style CRLF format, and one Unix-style LF. These exist precisely to detect corruption from newline conversion. https://stackoverflow.com/a/55425530/5700388

**Comment by caendesilva** [comment]
Closing again to keep the issues tab clear, and because this seems to be a general Git issue. If more people run into this, please do let me know!

**Comment by rominronin** [comment]
Sorry it took a while, been busy posting updates on my HydePHP enabled site ;)

`69f674565e3bebb467ece0e6c768223f89dc0b49de227da50580e7b1fd4b6239  podcast-cover-image.jpg
podcast-cover-image.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=9, PhotometricIntepretation=RGB, orientation=upper-left, xresolution=122, yresolution=130, resolutionunit=2, software=Snapseed 2.22.412829873, datetime=2023:04:20 12:19:01], baseline, precision 8, 1280x720, components 3
00000000: ffd8 ffe1 022e 4578 6966 0000 4d4d 002a  ......Exif..MM.*
00000010: 0000 0008 0009 0106 0003 0000 0001 0002  ................
00000020: 0000 0112 0003 0000 0001 0001 0000 011a  ................
00000030: 0005 0000 0001 0000 007a 011b 0005 0000  .........z......
00000040: 0001 0000 0082 0128 0003 0000 0001 0002  .......(........
00000050: 0000 0131 0002 0000 0018 0000 008a 0132  ...1...........2
00000060: 0002 0000 0014 0000 00a2 0213 0003 0000  ................
00000070: 0001 0001 0000 8769 0004 0000 0001 0000  .......i........
`

**Comment by caendesilva** [comment]
> Sorry it took a while, been busy posting updates on my HydePHP enabled site ;)

No worries at all! Going to take a look at this soon. Thank you so much for posting the data!

**Comment by caendesilva** [comment]
Okay, so I compared the data, and the images headers are the same (based on the initial bytes), and the metadata is too based on the file command data. However, since the checksum is different some bytes later on are changed, this ties in with my theory that it is line-ending related (Windows line endings are the bane of my existence).

Based on all this, **I think the fix for this issue is `*.png binary` to the `.gitattributes` file.**

This may not work directly for images already pushed due to how Git handles its history. But, I'm 92.5% sure that this is what the corruption is about. So please, if anyone in the future stumbles upon this, please let me know so I can get more data on it, especially if adding the binary line did not work.

**Comment by ydalton** [comment]
Hi, I just experienced the exact same issue. I use jpegs instead of pngs and I could see the streaking. I had a PDF file that was fully corrupted thanks to this. Can I ask why there is a `.gitattributes` to change CRLF to LF?

**Comment by caendesilva** [comment]
> Hi, please reopen this issue. I just experienced the exact same issue. I use jpegs instead of pngs and I could see the streaking. I had a PDF file that was fully corrupted thanks to this. Can I ask why there is a `.gitattributes` to change CRLF to LF?

Reopening to investigate. The reason we normalize CRLF to LF is to reduce cross-platform issues, as Windows systems use CRLF and Unix systems use LF, which can cause problems with file diffs. This is a great article on the history of this issue, with an anchor to the most relevant section: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#line-endings-in-git


Could you please confirm if adding `*.png binary` to the `.gitattributes` file solves this problem for you?

**Comment by ydalton** [comment]
> The reason we normalize CRLF to LF is to reduce cross-platform issues, as Windows systems use CRLF and Unix systems use LF, which can cause problems with file diffs. This is a great article on the history of this issue, with an anchor to the most relevant section: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#line-endings-in-git
> 
Alright, I've only seen messages relating to CRLF only on Windows, never on Linux or even Mac. Regarding the `.gitattributes` file, I think I only saw it in Laravel but it never caused issues there. Although it's slightly different, and with Laravel I've had no issues with binary files:
Laravel:
```
* text=auto eol=lf
```
HydePHP: 
```
* text eol=lf
```
> Could you please confirm if adding `*.png binary` to the `.gitattributes` file solves this problem for you?

Unfortunately, it doesn't work. I copy my files that are untouched into the `_media` folder, and I still get the warnings (and presumably the files begin corrupted).
```
pino@overbook-air:Documents/Projects/ydalton.github.io$ git add .
warning: in the working copy of '_media/CV_Dalton_Yussef.pdf', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of '_media/hambook.jpeg', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of '_media/php.jpg', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of '_media/work2.jpg', CRLF will be replaced by LF the next time Git touches it
```
My `.gitattributes` now looks like this:
```
* text eol=lf

*.blade.php diff=html
*.css diff=css
*.html diff=html
*.md diff=markdown
*.php diff=php

*.png binary

.github/ export-ignore
tests/ export-ignore
CHANGELOG.md export-ignore
LICENSE.md export-ignore
SECURITY.md export-ignore
```
I change the first line to what Laravel has:
```
* text=auto eol=lf
```
When I run `git add .` again I do not get the warnings. I've opened up a PR here.
https://github.com/hydephp/develop/pull/1700

**Comment by caendesilva** [comment]
Found out the context of why this only happened sometimes.

> Warning
> In some cases, files might be corrupted. This is a very rare case and none of the reporters made a reproducer available.
> 
> Git checks the first 8000 bytes of the file for a NUL "Character" to determine if the file is binary. Some binary file formats are more likely to contain 8000 bytes without 8 consecutive zero bits and should be marked as binary in the .gitattribute file to avoid that issue.

Source: https://stackoverflow.com/a/42135910/5700388
