### ISSUE TITLE
Undefined constant "Hyde\Foundation\Kernel\GLOB_BRACE"

### ISSUE THREAD

**Issue by sobi3ch** [hydephp/hyde#270]
OS: Fedora 41 (Workstation edition)
Kernel: x86_64 Linux 6.11.8-300.fc41.x86_64
PHP: 8.3.11
Composer: 2.8.3

Following instructions from instillation guide (https://hydephp.com/docs/1.x/)
```
composer create-project hyde/hyde
cd hyde
php hyde make:post
php hyde make:page
php hyde build

```

..when building I'm getting the following error:
```
 RuntimeException 

  An error occurred during the discovery process: Undefined constant "Hyde\Foundation\Kernel\GLOB_BRACE"

  at vendor/hyde/framework/src/Foundation/Concerns/BaseFoundationCollection.php:54
     50▕         try {
     51▕             $this->runDiscovery();
     52▕             $this->runExtensionHandlers();
     53▕         } catch (Throwable $exception) {
  ➜  54▕             throw new RuntimeException("An error occurred during the discovery process: {$exception->getMessage()}", previous: $exception);
     55▕         }
     56▕ 
     57▕         return $this;
     58▕     }

      +22 vendor frames 

  23  hyde:35
      LaravelZero\Framework\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

Is this a bug or I missing something?

**Comment by caendesilva** [comment]
Does your distro support PHP glob brace? Not all do, for example Alpine.

For this reason we will be moving away from using globs, and it's already on the backlog. 

It would be really helpful if you could confirm if this is because of that issue or if it's something else to investigate.

**Comment by sobi3ch** [comment]
> Does your distro support PHP glob brace? Not all do, for example Alpine.
Unfortunately it does not support glob brace

> 
> For this reason we will be moving away from using globs, and it's already on the backlog.
Great
> 
> It would be really helpful if you could confirm if this is because of that issue or if it's something else to investigate.
Done

**Comment by caendesilva** [comment]
@sobi3ch This fix is now released and can be used by updating to [HydePHP Framework v1.7.4](https://github.com/hydephp/framework/releases/tag/v1.7.4). Happy holidays!

**Comment by sobi3ch** [comment]
Thank you @caendesilva. Happy holidays as well. 🎄
